# -*- coding: utf-8 -*-
"""Assignment.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MSWe-EUn8-Jl3XZCpt-B6yi249klx2YH
"""

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
 
 
#if using termux
import subprocess
import shlex
#end if
 
#creating x,y for 3D plotting
xx, zz = np.meshgrid([-10,10], range(10))
#setting up plot
fig = plt.figure()
ax = fig.add_subplot(111,projection='3d')
 
 
#defining planes:  n.T * x = c 
n1 = np.array([0,1,0]).reshape((3,1))
A =  np.array([0,3,0]).reshape((3,1))
c1 = 3
 
#corresponding y for planes
y1 = (c1-n1[0]*xx-n1[2]*zz)/(n1[1])
 
#plotting planes
Plane=ax.plot_surface(xx, y1, zz,label="Plane", color='b',alpha=0.5)
Plane._facecolors2d=Plane._facecolors3d
Plane._edgecolors2d=Plane._edgecolors3d
 
#plotting point
ax.scatter(A[0],A[1],A[2],'o')
ax.text(0.2,1.2,0.2,'A') 
 
#show plot
plt.xlabel('$x$');plt.ylabel('$y$')
plt.legend(loc='best');
plt.grid()